# Generated by Django 2.2.10 on 2021-06-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_at',
            field=models.DateField(),
        ),
    ]
